<?php

function formmanager_form_alter(&$form, &$form_state, $form_id)
{
    if($form_id == 'user_login' )
    {
        $form['name']['#attributes']['class'][] = 'form-control';
        $form['pass']['#attributes']['class'][] = 'form-control';
        $form['actions']['submit']['#attributes']['class'][] = 'btn btn-primary btn-block btn-flat';
        //$form['submit']['#value'] = 'btn';
        $form['actions']['submit']['#value'] = 'Sign In';
        //$form['submit']['#suffix'] = '<p>Some text to place after the submit button</p>';
        $form['submit']['#suffix'] = '


                <div class="col-xs-4">';

        $form['submit']['#preffix'] ='</div>
            </div> <div class="clearfix"></div>';
        $options = array();
        $options[1] = "Yes";

        $form ['rememberme'] = array(
            '#type' => 'checkbox',
            '#title' => t('rememberme'),
            '#options' => $options,
            //'#access' => !empty($account->picture->fid),
            '#description' => t('Check this box to delete your current picture.'),
        );

    }

    if($form_id == 'user_pass')
    {
        $form['name']['#attributes']['class'][] = 'form-control';
        $form['pass']['#attributes']['class'][] = 'form-control';
        $form['actions']['submit']['#attributes']['class'][] = 'btn btn-primary btn-block btn-flat';
        //$form['submit']['#value'] = 'btn';
        $form['actions']['submit']['#value'] = 'Sign In';
        //$form['submit']['#suffix'] = '<p>Some text to place after the submit button</p>';
        $form['submit']['#suffix'] = '


                </div> <div class="clearfix"> <div class="col-xs-4">';

        $form['submit']['#preffix'] ='</div>
            </div> <div class="clearfix"></div>';



    }


}