<?php

/**
 * @file
 * formmanager.module
 */

// 50 items per page.
define('TOTAL_ITEMS_PER_PAGE_EVENT', 5);

// Admin uri links.
define('ADMIN_CONTENT_EVENT_MANAGE_URI', '/admin/content/event/manage/');
define('ADMIN_CONTENT_EVENT_EDIT_URI', 'admin/content/event/edit/');
define('ADMIN_CONTENT_EVENT_URI', '/admin/content/event/');

/**
 * Implements hook_entity_info().
 */
function event_entity_info() {
    $event_entity_info['event'] = array(
        'label' => t('Event'),
        'label callback' => 'event_label_callback',
        'entity class' => 'event',
        'controller class' => 'eventController',
        'base table' => 'event',
        'uri callback' => 'event_uri',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'event_id',
        ),
        'uri callback' => 'entity_class_uri',
        'load hook' => 'event_load',
        'static cache' => TRUE,
        'admin ui' => array(
          'path' => 'admin/content/event',
          'controller class' => 'eventUIController',
          'file' => 'includes/event.admin.inc',
        ),
        'module' => 'event',
        'access callback' => 'event_access_callback',
        'bundles' => array(
            'event' => array(
                'label' => 'Event',
                'admin' => array(
                    'path' => 'admin/structure/event/manage',
                    'access arguments' => array('administer event entities'),
                ),
            ),
        ),
        'views controller class' => 'EntityDefaultViewsController',
    );

    return $event_entity_info;
}




function event_menu() {
    $items = array();

    $items['event/%event'] = array(
        'title' => 'event manager',
        'page callback' => 'event_view_entity',
        'page arguments' => array(1),
        'access callback' => 'event_access_menu_callback',
        'access arguments' => array('view', 1),
    );

    $items['admin/content/event/bulk/delete/%'] = array(
        'title' => 'Bulk Delete delete',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('event_bulk_delete', 5),
        'access arguments' => array('administer event entities'),
        'file' => 'includes/event.admin.inc',
    );

    $items['admin/structure/event'] = array(
        'title' => 'Event Fields',
        'access arguments' => array('administer event entities'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}



/**
 * Implements hook_theme().
 */

function event_theme() {
    return array(
        'event_full' => array(
            'variables' => array('event' => NULL),
            'file' => 'includes/event.theme.inc',
        ),
    );
}





/**
 * Check access permission for Lawmakers Entity UI.
 */
function event_access_menu_callback($op, $lawmakers = NULL, $account = NULL) {
    switch ($op) {
        case 'view':
            return user_access('view event entities', $account);

        case 'create':
            return user_access('create event entities', $account);

        case 'update':
            return user_access('edit event entities', $account);

        case 'delete':
            return user_access('delete event entities', $account);
    }

    return FALSE;
}





/**
 * Help function api data.
 */
function event_locate_callback() {

    $params = drupal_get_query_parameters();

    if (isset($params['state'])) {
        $conditions = $params['state'];
        $result = event_entity_query($conditions);
        $data = event_load_multiple($result);
        drupal_json_output($data);
    }
    elseif (isset($params['party']) && isset($params['chamber'])) {
        $chamber = array('title' => $params['chamber']);
        $party = array('party' => $params['party']);
        $conditions = array_merge($party, $chamber);
        $result = event_entity_query($conditions);
        $data = event_load_multiple($result);
        drupal_json_output($data);
    }

}





/**
 * Custom controller for the lawmakers entity.
 */
class eventController extends EntityAPIController {

    /**
     * Override the save method.
     */
    public function save($entity, DatabaseTransaction $transaction = NULL) {
        if (isset($entity->is_new)) {
            $entity->created = REQUEST_TIME;
        }

        $entity->changed = REQUEST_TIME;
        return parent::save($entity, $transaction);
    }
}


function event_access_callback() {
    if (user_is_anonymous() && !user_access('administer event entities')) {
        return FALSE;
    }
    else {
        return TRUE;
    }
}

function event_permission() {
    return array(
        'administer event entities' => array(
            'title' => t('Administer Event Entities'),
            'description' => t('Allows a user to administer Event entities'),
        ),
        'view event entities' => array(
            'title' => t('View Event Entity'),
            'description' => t('Allows a user to view the Event entities.'),
        ),

    );
}


/**
 * Custom controller for the administrator UI.
 */
class eventUIController extends EntityDefaultUIController {

    /**
     * Override the menu hook for default ui controller.
     */
    public function hook_menu() {
        $items = parent::hook_menu();
        $items[$this->path]['title'] = t('Event');
        $items[$this->path]['description'] = t('Manage Event, including fields.');
        $items[$this->path]['access callback'] = 'event_access_callback';
        $items[$this->path]['access arguments'] = array('administer event entities');
        $items[$this->path]['type'] = MENU_LOCAL_TASK;
        return $items;
    }

    /**
     * Admin form for searching and doing bulk operations.
     */




    public function overviewForm($form, &$form_state) {
        //echo 656;
        $form['#prefix'] = '<div class="headingtext"><span>Event List</span></div>';
        $add='<span class="addimage" style="margin-bottom:5px;">'.l(t('Add Event'), ADMIN_CONTENT_EVENT_URI . 'add' ,array('query' => array('destination' => ADMIN_CONTENT_EVENT_MANAGE_URI))).'</span>';

        $header = array(
            //'contact_id' => array('data' => t('Contact  ID'), 'field' => 'contact_id'),
            'event_name' => array('data' => t('Event Name'), 'field' => 'event_name'),
            'event_status' => array('data' => t('Event Status'), 'field' => 'event_status'),
           // 'enquiry_type' => array('data' => t('Enquiry Type'), 'field' => 'enquiry_type'),
            'operations' => array('data' => t('Operations'), 'field' => 'operations'),
        );

        $options = array();
        $search_term = !empty($_GET['search']) ? $_GET['search'] : NULL;

        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'event');

        if (!empty($search_term)) {

            //var_dump($search_term);
            $query->propertyCondition('search_tag', '%' . $search_term . '%', 'like');
            //$query->propertyCondition('last_name', '%' . $search_term . '%', 'like','OR');
           // $query->propertyCondition('enquiry_type', '%' . str_replace(' ','_',$search_term) . '%', 'like');
        }
        // Check for sort order and sort key.
        if (!empty($_GET['sort']) && !empty($_GET['order'])) {
            $sort = strtoupper($_GET['sort']);
            $order = strtolower($_GET['order']);
            $order = str_replace(' ', '_', $order);
            if ($order != 'operations') {
                $query->propertyOrderBy($order, $sort);
            }
        }

        $query->pager(TOTAL_ITEMS_PER_PAGE_EVENT);

        $result = $query->execute();
       // var_dump($result);
        $event_results = !empty($result['event']) ? $result['event'] : array();
        $event_array = !empty($event_results) ? event_load_multiple(array_keys($event_results)) : array();

        //var_dump($contactus_array);
       // exit;
        foreach ($event_array as $event_id => $event) {
            $options['event_id-' . $event_id] = array(
                //'contact_id' => l($contactus->contact_id, 'contactus/' . $contactus->contact_id),
                'event_name' => l($event->event_name, 'event/' . $event->event_id),
                'event_status' => $event->event_status?'Active':'Deactive',
               // 'enquiry_type' => l(show_enquiry_in_detail($contactus->enquiry_type), 'contactus/' . $contactus->contact_id),
                'operations' =>
                    l(t('View'), 'event/' . $event->event_id) . '&nbsp;&nbsp;&nbsp;&nbsp;' .
                    l(t('Edit'), ADMIN_CONTENT_EVENT_MANAGE_URI . $event_id ,array('query' => array('destination' => ADMIN_CONTENT_EVENT_MANAGE_URI))) . '&nbsp;&nbsp;&nbsp;&nbsp;' .
                    l(t('Delete'), ADMIN_CONTENT_EVENT_MANAGE_URI . $event_id . '/delete', array('attributes' => array('class' => array('event-delete-' . $event->event_id), ), 'query' => array('destination' => ADMIN_CONTENT_EVENT_URI))),
            );
        }

        $form['search'] = array(
            '#type' => 'fieldset',
            '#title' => t('Basic Search'),
            '#collapsible' => TRUE,
            '#collapsed' => !empty($search_term) ? FALSE : TRUE,
        );

        $form['search']['search_text'] = array(
            '#type' => 'textfield',
            '#title' => t('Search Term'),
            '#default_value' => !empty($search_term) ? $search_term : '',
        );

        $form['search']['search_submit'] = array(
            '#type' => 'submit',
            '#value' => t('Search'),
        );

        $form['bulk_operations'] = array(
            '#type' => 'fieldset',
            '#title' => t('Bulk Operations'),
            '#collapsible' => TRUE,
            '#collapsed' => TRUE,
        );

        $form['bulk_operations']['operations'] = array(
            '#type' => 'select',
            '#options' => array(
                0 => t('Select a bulk operation'),
                'delete' => t('Delete selected event'),
            ),
        );

        $form['bulk_operations']['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Submit'),
        );

        $form['entities'] = array(
            '#type' => 'tableselect',
            '#header' => $header,
            '#options' => $options,
            '#attributes' => array('class' => array('entity-sort-table')),
            '#empty' => t('There are no event.'),
            '#prefix' =>$add,
        );
        $form['pager'] = array('#theme' => 'pager');
        drupal_set_title('Event List');

        return $form;
    }

    /**
     * Form Submit method.
     */
    public function overviewFormSubmit($form, &$form_state) {
        $values = $form_state['input'];
        $event_ids = array();

        if (!empty($values['entities'])) {
            foreach ($values['entities'] as $index => $value) {
                if (!empty($value)) {
                    $event_ids[] = str_replace('$event_ids-', '', $value);
                }
            }

            switch ($values['operations']) {
                case 'delete':

                    drupal_goto('admin/content/event/bulk/delete/' . implode('|', $event_ids));

 /*                   $form = array();
                    //$form_state['contact_ids'] = $contact_ids;
                    //var_dump($form_state['contact_ids']);
                    foreach($event_ids as $cid){
                        //echo 56;

                        $form_state['event_ids'][]=str_replace('event_id-','',$cid);

                    }

                    // print_r($form_state['contact_ids']);exit;
                    $contacts = contactus_load_multiple($form_state['event_ids']);
                    $variables = array(
                        'type' => 'ul',
                        'items' => array(),
                        'title' => '',
                        'attributes' => array(),
                    );

                    foreach ($contacts as $contact) {
                        echo $variables['items'][] = $contact->first_name;
                    }

                    event_delete_multiple($form_state['event_ids']);*/
                    break;
            }
        }

        if (!empty($values['search_text'])) {
            drupal_goto('admin/content/event', array('query' => array('search' => $values['search_text'])));
        }
    }

}


function event_entity_query($conditions = array()) {

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'event');

    // Apply conditions.
    foreach ($conditions as $key => $value) {
        $query->propertyCondition($key, $value);
    }

    $result = $query->execute();

    if (isset($result['event'])) {
        $event = array_keys($result['event']);
    }
    else {
        $event = array();
    }

    return $event;
}

/**
 * Label callback for lawmakers entities, for menu router, etc.
 */
function event_label_callback($event, $type) {
    return empty($event->event_name) ? 'Untitled Event' : $event->event_name;
}

/**
 * Saves Lawmaker to database.
 */
function event_save(event $event) {
    return $event->save();
}



function event_view_entity($event) {
    //echo 5656;
    //exit;
    $fullname = $event->event_name;
    drupal_set_title($fullname);
    // Path not entity.
    $event_output = theme('event_full', array('event' => $event));
    //var_dump($contact);
    return $event_output;
}




class event extends Entity {
    /**
     * Override defaultUri().
     */
    protected function defaultUri() {
        return array('path' => 'event/' . $this->identifier());
    }
}



/**
 * Menu autoloader for /lawmakers.
 */
function event_load($event_id, $reset = FALSE) {
    $events = event_load_multiple(array($event_id), array(), $reset);
    return reset($events);
}

/**
 * Load multiple lawmakers based on certain conditions.
 */
function event_load_multiple($event_id = array(), $conditions = array(), $reset = FALSE) {
    return entity_load('event', $event_id, $conditions, $reset);
}

/**
 * Deletes a lawmaker.
 */
function event_delete(event $events) {
    $events->delete();
}

/**
 * Delete multiple lawmakers.
 */
function event_delete_multiple(array $event__ids) {
    //var_dump($contact__ids);
    //exit;

    entity_get_controller('event')->delete($event__ids);
}

